name: Check

on:
  push:
    branches:
      - main
      - 'renovate/**'

  pull_request:
    branches:
      - main

  workflow_dispatch:
  workflow_call:

jobs:
  check:
    name: Check

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup pnpm
        uses: pnpm/action-setup@a3252b78c470c02df07e9d59298aecedc3ccdd6d # v3.0.0

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 20.17.0
          cache: pnpm

      - name: Install dependencies
        run: |
          pnpm install
          pnpm exec playwright install firefox --with-deps

      - name: Run check
        run: pnpm run check
